```{r}
#influenza national summary
infNatSum<-read.csv(file.choose())
A<-infNatSum$TOTAL.A
B<-infNatSum$TOTAL.B
weeks<-infNatSum$YEAR
positive_percent<-infNatSum$PERCENT.POSITIVE
a_percent<-infNatSum$PERCENT.A
b_percent<-infNatSum$PERCENT.B
col_length<-length(B)
data=matrix(B, nrow=1,ncol=col_length)
data<-rbind(data,A)
colnames(data)=weeks
rownames(data)=c("B","A")
# Get the stacked barplot
par(las=2)
par(mar=c(4,4,4,10))
barplot(data, col=c("darkgreen","yellow3") ,main="Influenza Positive tests reported by clinical labarotaries", ylim=c(0,20000),border="white",space=0.100, font.axis=1, xlab="Week", ylab="Number of Positive Specimens",font.lab=2)
legend(x=max(data)+0.5,fill=c("darkgreen","yellow3","black", "red","green"),legend=c("A","B","Percent Positive", "% Positive FLU A", "% Positive FLU B"),pch=1)
par(new=TRUE)
plot(positive_percent, type = "l", axes = FALSE, xlab = "", ylab="",col="black", font.axis=1)
axis(side=4, las=1,at=pretty(range(positive_percent)))
par(new=TRUE)
lines(a_percent, type = "l",col="red", font.axis=1)
par(new=TRUE)
lines(b_percent, type = "l",col="green", font.axis=1)
mtext("positive_percent", side=4,line=2)

```

```{r}
#influenza positive tested
infPosData<-read.csv(file.choose())
flu_a_h3<-infPosData$A..H3.
flu_a_2009<-infPosData$A..2009.H1N1.
flu_a_subtype<-infPosData$A..Subtyping.not.Performed.
flu_b<-infPosData$B
flu_h3<-infPosData$H3N2v
flu_bvic<-infPosData$BVic
flu_byam<-infPosData$BYam
weeks<-infPosData$YEAR
mat_data=matrix(flu_a_h3,nrow=1,ncol=length(flu_a_h3))
mat_data<-rbind(mat_data,flu_a_2009)
mat_data<-rbind(mat_data,flu_a_subtype)
mat_data<-rbind(mat_data,flu_b)
mat_data<-rbind(mat_data,flu_h3)
mat_data<-rbind(mat_data,flu_bvic)
mat_data<-rbind(mat_data,flu_byam)
colnames(mat_data)=weeks
rownames(mat_data)=c("A (H3)","A (2009 H1N1)","A (Subtyping not Performed)","B","H3N2v","BVic","BYam")
par(las=2)
barplot(mat_data,main="Influenza Positive tests categorized by subtype", col=c("darkgreen","green","red","pink","orange","yellow3","purple") , ylim=c(0,4000),border="white",space=0.100, font.axis=1, xlab="Week", ylab="Number of Positive Specimens",font.lab=2)
legend(x=max(mat_data)+0.5,fill=c("darkgreen","green","red","pink","orange","yellow3","purple"),legend=rownames(mat_data),pch=1)
```

```{r}
# influenza sub type
infSubtype<-read.csv(file.choose())


```

```{r}
#influenza heat map
library(ggplot2)
infHeatData<-read.csv(file.choose())
states <- map_data("state")
ACTIVITY.LEVEL=infHeatData$ACTIVITY.LEVEL
sim_data <- data.frame(region=unique(tolower(infHeatData$STATENAME)), ACTIVITY.LEVEL)
sim_data_geo <- merge(states, sim_data, by="region")
qplot(long, lat, main="2017-18 Influenza Season Week 4 ending Jan 27, 2018
",data=sim_data_geo, geom="polygon", fill=ACTIVITY.LEVEL, group=group)
 ```

```{r}
#influenza like illness data
iliData<-read.table(file.choose())
```

```{r}
#influenza mortality data
infMData<-read.csv(file.choose())
week<-infMData$Year
expe<-infMData$Expected

```

```{r}
#pediatric mortality data
ped_m_data<-read.csv(file.choose())
weeks<-ped_m_data$WEEK.NUMBER
prev_weeks_death<-ped_m_data$PREVIOUS.WEEKS.DEATHS
curr_weeks_death<-ped_m_data$CURRENT.WEEK.DEATHS
col_length<-length(prev_weeks_death)
data=matrix(prev_weeks_death, nrow=1,ncol=col_length)
data<-rbind(data,curr_weeks_death)
#colnames(data)=weeks
rownames(data)=c("Deaths Reported Previous Week","Deaths Reported Current Week")
 
# Get the stacked barplot
barplot(data,main="Number of Influenza-associated pediatric deaths",col=colors()[c(50,100)] , ylim=c(0,30),border="white", names.arg=weeks,space=0.100, legend=rownames(data), font.axis=1, xlab="Week of Death", ylab="number of deaths",font.lab=2)
```

